[tool.poetry]
name = "ztzp-concasys"
version = "0.1.0"
description = ""
authors = ["丁鹏飞 <544951985@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
